indent_style = "Visual"
use_small_heuristics = true
binop_separator = "Front"
combine_control_expr = true
comment_width = 0
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
fn_args_density = "Tall"
brace_style = "SameLineWhere"
empty_item_single_line = true
fn_single_line = false
where_single_line = true
force_explicit_abi = true
format_strings = true
hard_tabs = false
imports_indent = "Visual"
imports_layout = "Mixed"
match_block_trailing_comma = true
max_width = 200
merge_derives = true
force_multiline_blocks = false
newline_style = "Unix"
normalize_comments = true
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
reorder_extern_crates = true
reorder_extern_crates_in_group = false
reorder_modules = true
report_todo = "Never"
report_fixme = "Never"
skip_children = false
space_after_colon = true
space_before_colon = false
struct_field_align_threshold = 0
spaces_around_ranges = false
spaces_within_parens_and_brackets = false
struct_lit_single_line = true
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Compressed"
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
match_arm_blocks = true
write_mode = "Overwrite"
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
remove_blank_lines_at_start_or_end_of_block = true
